version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      my_network:
        ipv4_address: 10.10.10.2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      my_network:
        ipv4_address: 10.10.10.3

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28

volumes:
  postgres_data:
